services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: discord-bot
      POSTGRES_USER: discord-bot
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./seed.sql:/docker-entrypoint-initdb.d/zz-seed.sql
    ports:
      - '127.0.0.1:5432:5432/tcp'