// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EgsFreeGame struct {
	ID           int64
	StoreID      string
	Title        string
	Description  string
	Url          string
	ThumbnailUrl string
	StartDate    pgtype.Timestamptz
	EndDate      pgtype.Timestamptz
}

type WowTokenPrice struct {
	ID      int64
	Updated pgtype.Timestamptz
	Price   int64
}
